const translations = {
    en: {
        nav_secret_garden: "Secret Garden",
        nav_excursions: "Excursions",
        nav_water_sports: "Water Sports",
        nav_safari: "Safaris",
        nav_contact: "Contact Us",
        hero_title: "UNIQUE NATURE PARADISE",
        hero_desc: "Discover Zanzibar & Tanzania's most exquisite luxury tours, high-adrenaline water sports, and private sanctuary experiences in full freedom.",
        btn_book_vip: "Book VIP Experience",
        section_title: "Our Exclusive Experiences",
        title_1: "1. Zanzibar Excursions & Historic Tours",
        desc_1: "Visit giant Aldabra tortoises on Prison Island, sail on full-day Safari Blue with seafood buffets, explore Jozani Forest's rare monkeys, and walk Stone Town's historic streets.",
        title_2: "2. Jozani Natural Forest Discovery",
        desc_2: "Explore the lush tropical rainforest of Zanzibar, home to the endangered Red Colobus monkeys and unique nature trails.",
        title_3: "3. Equipment & Vehicle Rentals",
        desc_3: "High-end car rentals, scooters, quad bikes, snorkeling gear, underwater cameras, and sports equipment delivered straight to your hotel.",
        title_4: "4. Luxury Transporter & Transfers",
        desc_4: "VIP chauffeur transfers in luxury Alphards, Land Cruisers, and vans with complimentary Wi-Fi and air conditioning.",
        title_5: "5. UNP Fashion & Souvenir Boutique",
        desc_5: "Handcrafted organic artwork created using real dried banana leaves, custom designer beachwear, and authentic Zanzibar souvenirs.",
        title_6: "6. Tanzania Wildlife Safaris",
        desc_6: "Fly-in safaris departing directly from Zanzibar to Tanzania's world-famous national parks including flights, luxury lodges, and 4x4 game drives.",
        title_7: "7. Authentic City Tour",
        desc_7: "Explore local culture, street food markets, historical architecture, and experience daily life with expert local guides.",
        title_8: "8. Romantic Dinners & Honeymoon Packages",
        desc_8: "Candlelit beachfront dinners, sunset dhow dinner cruises, live music, fresh seafood menus, and exclusive romantic setups.",
        title_9: "9. Jet Ski, Jet Car & Drone Kayak",
        desc_9: "High-speed luxury marine Jet Cars and Jet Skis, alongside transparent clear kayaks paired with aerial drone video recording.",
        title_10: "10. Secret Garden (The Private Oasis)",
        desc_10: "An ultra-private secluded sanctuary designed for high-profile guests seeking 100% discretion, private butler service, and total freedom.",
        footer_desc: "10-Star luxury, adventure, and sanctuary experiences in Zanzibar & Tanzania.",
        footer_contact: "Direct Contact"
    },
    it: {
        nav_secret_garden: "Giardino Segreto",
        nav_excursions: "Escursioni",
        nav_water_sports: "Sport Acquatici",
        nav_safari: "Safari",
        nav_contact: "Contattaci",
        hero_title: "UNIQUE NATURE PARADISE",
        hero_desc: "Scopri i tour di lusso più esclusivi di Zanzibar e della Tanzania, sport acquatici ad alta scarica di adrenalina ed esperienze private in totale libertà.",
        btn_book_vip: "Prenota Esperienza VIP",
        section_title: "Le Nostre Esperienze Esclusive",
        title_1: "1. Escursioni a Zanzibar e Tour Storici",
        desc_1: "Visita le tartarughe giganti ad Prison Island, naviga con Safari Blue con buffet di frutti di mare, esplora la foresta di Jozani e la storica Stone Town.",
        title_2: "2. Scoperta della Foresta Naturale di Jozani",
        desc_2: "Esplora la lussureggiante foresta pluviale tropicale di Zanzibar, dimora dei rari colobi rossi e di sentieri naturalistici unici.",
        title_3: "3. Noleggio Attrezzature e Veicoli",
        desc_3: "Noleggio auto di lusso, scooter, quad, attrezzatura da snorkeling, fotocamere subacquee e attrezzatura sportiva consegnati direttamente al tuo hotel.",
        title_4: "4. Trasporti di Lusso e Trasferimenti",
        desc_4: "Trasferimenti VIP con autista in auto di lusso, Alphard e Land Cruiser con Wi-Fi gratuito e aria condizionata.",
        title_5: "5. Boutique di Moda e Souvenir UNP",
        desc_5: "Opere d'arte artigianali create con vere foglie di banana essiccate, abbigliamento da spiaggia su misura e souvenir autentici di Zanzibar.",
        title_6: "6. Safari nella Fauna Selvatica della Tanzania",
        desc_6: "Safari con volo diretto da Zanzibar verso i parchi nazionali famosi in tutto il mondo, inclusi voli, lodge di lusso e safari in 4x4.",
        title_7: "7. Tour Autentico della Città",
        desc_7: "Esplora la cultura locale, i mercati del cibo di strada, l'architettura storica e vivi la vita quotidiana con guide locali esperte.",
        title_8: "8. Cene Romantiche e Pacchetti Luna di Miele",
        desc_8: "Cene a lume di candela sulla spiaggia, crociere al tramonto con cena su dhow, musica dal vivo e menu a base di frutti di mare freschi.",
        title_9: "9. Moto d'Acqua, Jet Car e Kayak con Drone",
        desc_9: "Jet Car e moto d'acqua di lusso ad alta velocità, insieme a kayak trasparenti con riprese video aeree da drone.",
        title_10: "10. Giardino Segreto (Oasi Privata)",
        desc_10: "Un santuario ultra-privato progettato per ospiti VIP che cercano la massima discrezione, servizio di maggiordomo privato e totale libertà.",
        footer_desc: "Lusso a 10 stelle, avventura e rifugio privato a Zanzibar e Tanzania.",
        footer_contact: "Contatto Diretto"
    },
    fr: {
        nav_secret_garden: "Jardin Secret",
        nav_excursions: "Excursions",
        nav_water_sports: "Sports Nautiques",
        nav_safari: "Safaris",
        nav_contact: "Contactez-nous",
        hero_title: "UNIQUE NATURE PARADISE",
        hero_desc: "Découvrez les circuits de luxe les plus exclusifs de Zanzibar et de Tanzanie, des sports nautiques à forte adrénaline et des sanctuaires privés en toute liberté.",
        btn_book_vip: "Réserver une Expérience VIP",
        section_title: "Nos Expériences Exclusives",
        title_1: "1. Excursions à Zanzibar et Visites Historiques",
        desc_1: "Visitez les tortues géantes à Prison Island, naviguez sur Safari Blue avec buffet de fruits de mer, explorez la forêt de Jozani et Stone Town.",
        title_2: "2. Découverte de la Forêt Naturelle de Jozani",
        desc_2: "Explorez la forêt tropicale luxuriante de Zanzibar, refuge des singes Colobes Rouges menacés et de sentiers botaniques uniques.",
        title_3: "3. Location d'Équipements et de Véhicules",
        desc_3: "Location de voitures haut de gamme, scooters, quads, matériel de plongée, caméras sous-marines livrés directement à votre hôtel.",
        title_4: "4. Transport de Luxe et Transferts",
        desc_4: "Transferts VIP avec chauffeur dans des véhicules de luxe Alphard et Land Cruiser avec Wi-Fi gratuit et climatisation.",
        title_5: "5. Boutique de Mode et Souvenirs UNP",
        desc_5: "Œuvres d'art artisanales réalisées avec de vraies feuilles de bananier séchées, vêtements de plage sur mesure et souvenirs authentiques de Zanzibar.",
        title_6: "6. Safaris Animaliers en Tanzanie",
        desc_6: "Safaris par avion au départ direct de Zanzibar vers les parcs nationaux renommés, incluant vols, lodges de luxe et excursions 4x4.",
        title_7: "7. Visite Authentique de la Ville",
        desc_7: "Découvrez la culture locale, les marchés de rue, l'architecture historique et la vie quotidienne avec des guides locaux experts.",
        title_8: "8. Dîners Romantiques et Lunes de Miel",
        desc_8: "Dîners aux chandelles sur la plage, croisières au coucher du soleil en dhow, musique en direct et menus gourmands de fruits de mer.",
        title_9: "9. Jet Ski, Jet Car et Kayak Transparent",
        desc_9: "Jet Cars et Jet Skis marins de luxe à grande vitesse, ainsi que des kayaks transparents associés à un enregistrement vidéo par drone.",
        title_10: "10. Jardin Secret (Oasis Privée)",
        desc_10: "Un sanctuaire ultra-privé conçu pour les invités de marque recherchant une discrétion absolue, un service de majordome dédié et une liberté totale.",
        footer_desc: "Luxe 10 étoiles, aventure et sanctuaire privé à Zanzibar et en Tanzanie.",
        footer_contact: "Contact Direct"
    },
    ru: {
        nav_secret_garden: "Тайный Сад",
        nav_excursions: "Экскурсии",
        nav_water_sports: "Водный Спорт",
        nav_safari: "Сафари",
        nav_contact: "Контакты",
        hero_title: "UNIQUE NATURE PARADISE",
        hero_desc: "Откройте для себя самые эксклюзивные роскошные туры Занзибара и Танзании, захватывающий водный спорт и личные оазисы в полной свободе.",
        btn_book_vip: "Забронировать VIP Отдых",
        section_title: "Наши Эксклюзивные Услуги",
        title_1: "1. Экскурсии по Занзибару и Исторические Туры",
        desc_1: "Посетите гигантских черепах на острове Призон, отправляйтесь в морской тур Safari Blue с обедом из морепродуктов, исследуйте лес Джозани и Стоун-Таун.",
        title_2: "2. Исследование Природного Леса Джозани",
        desc_2: "Исследуйте пышные тропические леса Занзибара, где обитают редкие обезьяны Красные Колобусы.",
        title_3: "3. Аренда Техники и Снаряжения",
        desc_3: "Аренда элитных автомобилей, скутеров, квадроциклов, снаряжения для сноркелинга и подводных камер с доставкой в отель.",
        title_4: "4. Роскошный Трансфер и Транспорт",
        desc_4: "VIP-трансферы с личным водителем на премиальных авто Alphard и Land Cruiser с Wi-Fi и кондиционером.",
        title_5: "5. Бутик Моды и Сувениров UNP",
        desc_5: "Картины ручной работы из сушеных банановых листьев, дизайнерская пляжная одежда и аутентичные сувениры Занзибара.",
        title_6: "6. Сафари по Дикой Природе Танзании",
        desc_6: "Авиа-сафари прямо из Занзибара в знаменитые национальные парки, включая перелеты, элитные лоджи и поездки на джипах 4x4.",
        title_7: "7. Аутентичный Экскурсионный Тур",
        desc_7: "Погрузитесь в местную культуру, уличные рынки, историческую архитектуру и повседневную жизнь с опытными гидами.",
        title_8: "8. Романтические Ужины и Медовый Месяц",
        desc_8: "Ужины при свечах на пляже, круизы на закате на деревянной лодке Доу, живая музыка и свежие морепродукты.",
        title_9: "9. Джет-Ски, Джет-Кар и Прозрачный Каяк",
        desc_9: "Скоростные морские джет-кары и гидроциклы, а также прозрачные каяки с аэросъемкой с квадрокоптера.",
        title_10: "10. Тайный Сад (Частный Оазис)",
        desc_10: "Уединенный оазис для VIP-гостей, которым требуется 100% конфиденциальность, личный дворецкий и полная свобода.",
        footer_desc: "10-звездочный роскошный отдых, приключения и уединение на Занзибаре и в Танзании.",
        footer_contact: "Прямые Контакты"
    },
    de: {
        nav_secret_garden: "Geheimer Garten",
        nav_excursions: "Ausflüge",
        nav_water_sports: "Wassersport",
        nav_safari: "Safaris",
        nav_contact: "Kontakt",
        hero_title: "UNIQUE NATURE PARADISE",
        hero_desc: "Entdecken Sie Sansibars und Tansanias exklusivste Luxustouren, adrenalingeladenen Wassersport und private Schutzgebiete in voller Freiheit.",
        btn_book_vip: "VIP-Erlebnis Buchen",
        section_title: "Unsere Exklusiven Erlebnisse",
        title_1: "1. Sansibar Ausflüge & Historische Touren",
        desc_1: "Besuchen Sie Riesenschildkröten auf Prison Island, segeln Sie einen ganzen Tag mit Safari Blue inkl. Meeresfrüchte-Buffet und erkunden Sie den Jozani-Wald.",
        title_2: "2. Jozani-Wald Entdeckungstour",
        desc_2: "Erkunden Sie den üppigen tropischen Regenwald Sansibars, die Heimat der seltenen Roten Stummelaffen.",
        title_3: "3. Fahrzeug- & Ausrüstungsverleih",
        desc_3: "Hochwertige Mietwagen, Roller, Quads, Schnorchelausrüstung und Unterwasserkameras direkt zu Ihrem Hotel geliefert.",
        title_4: "4. Luxus-Transfers & Chauffeur-Service",
        desc_4: "VIP-Chauffeur-Transfers in Luxusfahrzeugen wie Alphard und Land Cruiser mit kostenlosem WLAN und Klimaanlage.",
        title_5: "5. UNP Mode & Souvenir Boutique",
        desc_5: "Handgefertigte Kunstwerke aus echten getrockneten Bananenblättern, maßgeschneiderte Strandmode und authentische Souvenirs.",
        title_6: "6. Tansania Wildtier-Safaris",
        desc_6: "Flugsafaris direkt von Sansibar in die weltberühmten Nationalparks Tansanias inkl. Flügen, Luxus-Lodges und 4x4-Geländewagen.",
        title_7: "7. Authentische Stadtführung",
        desc_7: "Erkunden Sie die lokale Kultur, Straßenmärkte, historische Architektur und das tägliche Leben mit sachkundigen Führern.",
        title_8: "8. Romantische Abendessen & Flitterwochen",
        desc_8: "Romantische Abendessen am Strand bei Kerzenschein, Dhow-Fahrten zum Sonnenuntergang, Live-Musik und frische Meeresfrüchte.",
        title_9: "9. Jetski, Jet Car & Drohnen-Kajak",
        desc_9: "Hochgeschwindigkeits-Jet-Cars und Jetskis sowie transparente Kajaks inklusive Luftaufnahmen per Drohne.",
        title_10: "10. Geheimer Garten (Private Oase)",
        desc_10: "Ein hochprivater, abgelegener Rückzugsort für VIP-Gäste, die 100% Diskretion, privaten Butler-Service und totale Freiheit suchen.",
        footer_desc: "10-Sterne-Luxus, Abenteuer und private Erholung auf Sansibar & Tansania.",
        footer_contact: "Direkter Kontakt"
    },
    es: {
        nav_secret_garden: "Jardín Secreto",
        nav_excursions: "Excursiones",
        nav_water_sports: "Deportes Acuáticos",
        nav_safari: "Safariss",
        nav_contact: "Contacto",
        hero_title: "UNIQUE NATURE PARADISE",
        hero_desc: "Descubra los tours de lujo más exclusivos de Zanzíbar y Tanzania, deportes acuáticos de alta adrenalina y santuarios privados en total libertad.",
        btn_book_vip: "Reservar Experiencia VIP",
        section_title: "Nuestras Experiencias Exclusivas",
        title_1: "1. Excursiones en Zanzíbar y Tours Históricos",
        desc_1: "Visite tortugas gigantes en Prison Island, navegue en Safari Blue con buffet de mariscos y explore el bosque de Jozani y Stone Town.",
        title_2: "2. Descubrimiento del Bosque Natural de Jozani",
        desc_2: "Explore la frondosa selva tropical de Zanzíbar, hogar del raro mono colobo rojo y senderos naturales únicos.",
        title_3: "3. Alquiler de Equipos y Vehículos",
        desc_3: "Alquiler de coches de alta gama, scooters, quads, equipo de esnórquel y cámaras submarinas entregados en su hotel.",
        title_4: "4. Transporte de Lujo y Traslados",
        desc_4: "Traslados VIP con chófer en vehículos Alphard y Land Cruiser de lujo con Wi-Fi gratuito y aire acondicionado.",
        title_5: "5. Boutique de Moda y Souvenirs UNP",
        desc_5: "Obras de arte hechas a mano con hojas de plátano secas, ropa de playa de diseño y recuerdos auténticos de Zanzíbar.",
        title_6: "6. Safaris de Vida Silvestre en Tanzania",
        desc_6: "Safaris en avión saliendo desde Zanzíbar hacia los parques nacionales de Tanzania, incluyendo vuelos, lodges de lujo y 4x4.",
        title_7: "7. Tour Auténtico por la Ciudad",
        desc_7: "Explore la cultura local, los mercados callejeros de comida, la arquitectura histórica y la vida cotidiana con guías locales expertos.",
        title_8: "8. Cenas Románticas y Luna de Miel",
        desc_8: "Cenas a la luz de las velas en la playa, cruceros en dhow al atardecer, música en vivo y menús de mariscos frescos.",
        title_9: "9. Moto de Agua, Jet Car y Kayak con Dron",
        desc_9: "Jet Cars y motos de agua de lujo a alta velocidad, junto con kayaks transparentes con grabación de video con dron.",
        title_10: "10. Jardín Secreto (Oasis Privado)",
        desc_10: "Un santuario ultra privado diseñado para clientes VIP que buscan un 100% de discreción, servicio de mayordomo y libertad total.",
        footer_desc: "Lujo de 10 estrellas, aventura y santuario privado en Zanzíbar y Tanzania.",
        footer_contact: "Contacto Directo"
    },
    zh: {
        nav_secret_garden: "秘密花园",
        nav_excursions: "远足远游",
        nav_water_sports: "水上运动",
        nav_safari: "游猎之旅",
        nav_contact: "联系我们",
        hero_title: "UNIQUE NATURE PARADISE",
        hero_desc: "探索桑给巴尔和坦桑尼亚最顶级的奢华之旅、充满刺激的水上运动以及完全自由的私人圣所体验。",
        btn_book_vip: "预订 VIP 体验",
        section_title: "我们的专属体验",
        title_1: "1. 桑给巴尔远足与历史之旅",
        desc_1: "在监狱岛观赏巨龟，在 Safari Blue 享用海鲜自助餐，探索约扎尼森林的稀有红考布斯猴，漫步石头城历史老街。",
        title_2: "2. 约扎尼原始森林探索",
        desc_2: "探索桑给巴尔茂密的热带雨林，这里是濒危红考布斯猴的家园，拥有独特的大自然小径。",
        title_3: "3. 车辆与设备租赁",
        desc_3: "高端租车、速珂摩托、四轮越野车、潜水装备、水下相机及运动器材直接送达您的酒店。",
        title_4: "4. 奢华客运与接送",
        desc_4: "提供 Alphard、陆地巡洋舰等奢华车型的 VIP 专车接送服务，配备免费 Wi-Fi 和空调。",
        title_5: "5. UNP 时尚与纪念品精品店",
        desc_5: "利用真实干燥香蕉叶纯手工制作的艺术品、定制设计师海滩装及正宗桑给巴尔纪念品。",
        title_6: "6. 坦桑尼亚野生动物游猎",
        desc_6: "从桑给巴尔直飞坦桑尼亚著名国家公园的飞行游猎，包含机票、奢华营地及 4x4 驱车体验。",
        title_7: "7. 地道城市之旅",
        desc_7: "与专业当地导游一起探索当地文化、街头美食市场、历史建筑并体验日常生活。",
        title_8: "8. 浪漫晚餐与蜜月套餐",
        desc_8: "海滩烛光晚餐、日落帆船晚餐巡游、现场音乐、新鲜海鲜菜单和专属浪漫布置。",
        title_9: "9. 摩托艇、水上跑车与航拍划艇",
        desc_9: "高速奢华水上跑车 (Jet Car) 和水上摩托艇，以及配备航拍无人机录制的透明水上划艇。",
        title_10: "10. 秘密花园（私人绿洲）",
        desc_10: "为寻求 100% 隐私、私人管家服务和完全自由的高端贵宾量身定制的顶级隐秘圣所。",
        footer_desc: "桑给巴尔和坦桑尼亚的十星级奢华、冒险与私人圣所体验。",
        footer_contact: "直接联系"
    },
    ar: {
        nav_secret_garden: "الحديقة السرية",
        nav_excursions: "الرحلات",
        nav_water_sports: "الرياضات المائية",
        nav_safari: "السفاري",
        nav_contact: "اتصل بنا",
        hero_title: "UNIQUE NATURE PARADISE",
        hero_desc: "اكتشف أفخم الجولات السياحية في زنجبار وتنزانيا، والرياضات المائية المليئة بالإثارة، والتجارب الخاصة في ملاذ آمن بكل حرية.",
        btn_book_vip: "حجز تجربة VIP",
        section_title: "تجاربنا الحصرية",
        title_1: "1. رحلات زنجبار والجولات التاريخية",
        desc_1: "قم بزيارة السلاحف العملاقة في جزيرة بريزون، وأبحر في رحلة "سفاري بلو" مع بوفيه المأكولات البحرية، واستكشف غابة جوزاني وستون تاون.",
        title_2: "2. اكتشاف غابة جوزاني الطبيعية",
        desc_2: "استكشف الغابات المطيرة الاستوائية المورقة في زنجبار، موطن قرود الكولوبوس الحمراء النادرة والمسارات الطبيعية الفريدة.",
        title_3: "3. تأجير المعدات والمركبات",
        desc_3: "تأجير سيارات فاخرة، دراجات نارية، دبابات، معدات الغوص، وكاميرات تحت الماء يتم تسليمها مباشرة إلى فندقك.",
        title_4: "4. وسائل النقل الفاخرة والتوصيل",
        desc_4: "خدمات نقل VIP مع سائق في سيارات الفارد ولاند كروزر فاخرة مع خدمة الواي فاي والتكييف مجانًا.",
        title_5: "5. بوتيك UNP للأزياء الهدايا التذكارية",
        desc_5: "أعمال فنية مصنوعة يدويًا باستخدام أوراق الموز المجففة الحقيقية، وملابس شاطئ مصممة خصيصًا، وهدايا تذكارية أصيلة.",
        title_6: "6. رحلات السفاري البرية في تنزانيا",
        desc_6: "رحلات سفاري طيران تنطلق مباشرة من زنجبار إلى المتنزهات الوطنية الشهيرة بما في ذلك الطيران، النزل الفاخرة، وجولات 4x4.",
        title_7: "7. جولة المدينة الأصيلة",
        desc_7: "استكشف الثقافة المحلية، وأسواق المأكولات الشعبية، والمعمار التاريخي، واختبر الحياة اليومية مع مرشدين محليين خبراء.",
        title_8: "8. العشاء الرومانسي وباقات شهر العسل",
        desc_8: "عشاء على ضوء الشموع على الشاطئ، ورحلات العشاء عند الغروب، وموسيقى حية، وقوائم مأكولات بحرية طازجة.",
        title_9: "9. الجيت سكي، سيارات الماء، والكياك الشفاف",
        desc_9: "سيارات مائية فاخرة وسريعة وجيت سكي، بالإضافة إلى قوارب كاياك شفافة مع تصوير بالفيديو عبر الطائرات بدون طيار.",
        title_10: "10. الحديقة السرية (الواحة الخاصة)",
        desc_10: "ملاذ منعزل وفائق الخصوصية مصمم للضيوف كبار الشخصيات الذين يبحثون عن السرية التامة 100%، وخدمة الخادم الشخصي.",
        footer_desc: "تجارب الفخامة بـ 10 نجوم والمغامرة والملاذ الخاص في زنجبار وتنزانيا.",
        footer_contact: "الاتصال المباشر"
    },
    nl: {
        nav_secret_gar