const frTranslation = {
heroTitle: "UNP TOURS ZANZIBAR",
heroDesc: "Decouvrez les circuits de luxe les plus exquis de Zanzibar et de Tanzanie, les sports nautiques, l'artisanat et les experiences de sanctuaire prive en toute liberte.",
heroBtn: "Reserver l'Experience VIP",
secTitle: "Nos Experiences Exclusives",
navExcursions: "Excursions",
navWater: "Sports Nautiques",
navSafari: "Safaris",
navArt: "Boutique",
navGarden: "Jardin Secret",
navVote: "Voter",
navVip: "VIP",
navBook: "Reserver",
navContact: "Contact",
navAbout: "A Propos",
navGallery: "Galerie",
card1Title: "1. Excursions a Zanzibar & Circuits Historiques",
card1Desc: "Visitez les tortues geantes sur l'ile Prison, naviguez sur Safari Blue et parcourez Stone Town.",
card2Title: "2. Sanctuaire des Singes Colobes de Jozani",
card2Desc: "Explorez le parc national de Jozani et rencontrez les rares singes colobes rouges.",
card3Title: "3. Location d'Equipement & Vehicules",
card3Desc: "Location de voitures, scooters, quads, equipement de plongee et cameras a votre hotel.",
card4Title: "4. Transport de Luxe & Transferts",
card4Desc: "Transferts VIP avec chauffeur en Alphards, Land Cruisers et vans avec Wi-Fi et climatisation.",
card5Title: "5. Oeuvres d'Art en Feuilles de Bananier",
card5Desc: "Oeuvres d'art avec des feuilles de bananier sechees, representant la faune africaine.",
card6Title: "6. Safaris Fauniques en Tanzanie",
card6Desc: "Safaris en avion de Zanzibar vers les parcs nationaux de Tanzanie, avec vols et lodges.",
card7Title: "7. Visite Authentique de la Ville",
card7Desc: "Explorez la culture locale, les marches de rue et l'architecture historique avec des guides experts.",
card8Title: "8. Diner Romantique au Coucher du Soleil",
card8Desc: "Diner prive aux chandelles sur des plages de sable blanc avec musique live.",
card9Title: "9. Jet Ski, Jet Car & Kayak Drone",
card9Desc: "Jet Cars et Jet Skis de luxe, ainsi que des kayaks transparents avec video par drone.",
card10Title: "10. Jardin Secret (L'Oasis Privee)",
card10Desc: "Sanctuaire prive ultra-secret pour les clients de haut profil recherchant une discretion totale.",
aboutHeading: "A Propos d'UNP Tours",
aboutDesc: "Unique & Natural Paradise (UNP) est un operateur de tourisme de luxe base a Zanzibar, en Tanzanie.",
aboutText1: "Fonde avec la passion de mettre en valeur le meilleur de Zanzibar et de la Tanzanie, UNP Tours propose une collection d'experiences exclusives.",
aboutText2: "Notre equipe d'experts locaux se consacre a fournir un service personnalise, en veillant a ce que chaque voyage soit adapte a vos desirs.",
galleryHeading: "Notre Galerie",
galleryDesc: "Explorez la beaute de Zanzibar et de la Tanzanie a travers notre objectif.",
voteHeading: "Votez pour Votre Experience UNP Preferee",
voteDesc: "Aidez-nous a mieux vous servir ! Notez votre activite preferee :",
lblSelectExp: "Choisissez l'Experience :",
lblRateStars: "Notez Votre Experience (1 a 5 Etoiles) :",
btnVoteSubmit: "Soumettre l'Evaluation",
vipHeading: "EXPERIENCE DE LUXE UNP VIP",
vipDesc: "Profitez d'une discretion maximale, de vols prives, d'un majordome personnel et de circuits de luxe sur mesure.",
vipF1: "100% Discretion",
vipF1Sub: "Enregistrement prive et non-divulgation.",
vipF2: "Vols Prives",
vipF2Sub: "Transferts et safaris charter sur l'ile.",
vipF3: "Majordome Prive",
vipF3Sub: "Concierge personnel dedie 24h/24.",
btnVipReq: "Reserver un Concierge VIP",
bookHeading: "Formulaire de Reservation en Ligne",
bookDesc: "Reservez vos circuits, concierge VIP ou jardin secret via WhatsApp :",
lblGuestName: "Nom Complet :",
lblGuestContact: "Email / Numero de Telephone :",
lblGuestService: "Selectionnez l'Experience :",
lblGuestDate: "Date Souhaitee :",
lblGuestCount: "Nombre d'Invites :",
lblGuestNotes: "Demandes Speciales :",
btnBookSubmit: "Soumettre la Reservation via WhatsApp",
footerAbout: "Luxe 10 etoiles, aventure, oeuvres d'art artisanales a Zanzibar et en Tanzanie.",
footerContactHead: "Contact Direct"
};
