const ruTranslation = {
heroTitle: "UNP TOURS ZANZIBAR",
heroDesc: "Otkroyte dlya sebya samye izyskannye lyuksovye tury Zanzibara i Tanzanii, vodnye vidy sporta, izdeliya ruchnoy raboty i chastnye ubezhishcha v polnoy svobode.",
heroBtn: "Zabronirovat VIP-Opyt",
secTitle: "Nashi Ekcklyuzivnye Vpechatleniya",
navExcursions: "Ekskursii",
navWater: "Vodnye Vidy Sporta",
navSafari: "Safari",
navArt: "Butik",
navGarden: "Taynyy Sad",
navVote: "Golosovanie",
navVip: "VIP",
navBook: "Bronirovat",
navContact: "Kontakt",
navAbout: "O Nas",
navGallery: "Galereya",
card1Title: "1. Ekskursii po Zanzibaru i Istoricheskie Tury",
card1Desc: "Posetite gigantskikh cherepakh na ostrove-tyurme, prokatites na Safari Blue i progulyaytes po Stountaunu.",
card2Title: "2. Zapovednik Krasnykh Kolobusov Dzhozani",
card2Desc: "Issleduyte natsionalnyy park Dzhozani i vstrette redkikh krasnykh kolobusov.",
card3Title: "3. Prokat Snaryazheniya i Transporta",
card3Desc: "Arenda avtomobiley, skuterov, kvadrotsiklov, snaryazheniya dlya snorklinga s dostavkoy v otel.",
card4Title: "4. Lyuksovyy Transport i Transfery",
card4Desc: "VIP-transfery s voditelem na lyuksovykh Alphard, Land Cruiser i mikroavtobusakh.",
card5Title: "5. Izdeliya iz Bananovykh Listev",
card5Desc: "Izdeliya ruchnoy raboty iz sushenykh bananovykh listev, izobrazhayushchie afrikanskuyu prirodu.",
card6Title: "6. Safari po Dikoy Prirode Tanzanii",
card6Desc: "Aviasafari iz Zanzibara v natsionalnye parki Tanzanii, vklyuchaya perelety i lyuksovye lodzhi.",
card7Title: "7. Autentichnyy Tur po Gorodu",
card7Desc: "Issleduyte mestnuyu kulturu, ulichnye rynki i istoricheskuyu arkhitekturu s gidami.",
card8Title: "8. Romanticheskiy Uzhin na Zakate",
card8Desc: "Chastnyy uzhin pri svechakh na belykh plyazhakh pod zvezdami s zhivoy muzykoy.",
card9Title: "9. Gidrotsikl, Dzhet Kar i Kayak s Dronom",
card9Desc: "Lyuksovye dzhet-kary i gidrotsikly, a takzhe prozrachnye kayaki s aerosemkoy dronom.",
card10Title: "10. Taynyy Sad (Chastnyy Oazis)",
card10Desc: "Ultra-chastnoe ubezhishche dlya vysokopostavlennykh gostey, ishchushchikh konfidentsialnost.",
aboutHeading: "O Nas - UNP Tours",
aboutDesc: "Unique & Natural Paradise (UNP) - eto vedushchiy operator lyuksovykh turov, baziruyushchiysya na Zanzibare, Tanzaniya.",
aboutText1: "Osnovannaya so strastyu pokazat luchshee Zanzibara i Tanzanii, UNP Tours predlagaet tshchatelno podobrannuyu kollektsiyu ekcklyuzivnykh vpechatleniy.",
aboutText2: "Nasha komanda mestnykh ekspertov stremitsya predostavit personalizirovannyy servis, garantiruya, chto kazhdoe puteshestvie budet sootvetstvovat vashim zhelaniyam.",
galleryHeading: "Nasha Galereya",
galleryDesc: "Issleduyte krasotu Zanzibara i Tanzanii cherez nash obektiv.",
voteHeading: "Golosuyte za Vash Lyubimyy Opyt UNP",
voteDesc: "Pomogite nam luchshe sluzhit vam! Otsenite vashe lyubimoe zanyatie:",
lblSelectExp: "Vyberite Opyt:",
lblRateStars: "Otsenite Vash Opyt (1-5 Zvezd):",
btnVoteSubmit: "Otpravit Otsenku",
vipHeading: "LYUKSOVYY OPYT UNP VIP",
vipDesc: "Naslazhdaytes konfidentsialnostyu, chastnymi aviareysami, lichnym dvoretskim i lyuksovymi turami.",
vipF1: "100% Konfidentsialnost",
vipF1Sub: "Chastnaya registratsiya i nerazglashenie.",
vipF2: "Chastnye Reysy",
vipF2Sub: "Charternye transfery i safari po ostrovu.",
vipF3: "Lichnyy Dvoretskiy",
vipF3Sub: "Personalnyy konserzh 24/7.",
btnVipReq: "Zabronirovat VIP-Konserzha",
bookHeading: "Forma Onlayn-Bronirovaniya",
bookDesc: "Zabroniruyte tury, VIP-konserzha ili Taynyy Sad cherez WhatsApp:",
lblGuestName: "Polnoe Imya:",
lblGuestContact: "El. Pochta / Telefon:",
lblGuestService: "Vyberite Opyt:",
lblGuestDate: "Zhelaemaya Data:",
lblGuestCount: "Kolichestvo Gostey:",
lblGuestNotes: "Osobye Pozhelaniya:",
btnBookSubmit: "Otpravit Bronirovanie cherez WhatsApp",
footerAbout: "10-zvezdnochnyy lyuks, priklyucheniya, izdeliya ruchnoy raboty na Zanzibare i v Tanzanii.",
footerContactHead: "Pryamoy Kontakt"
};
