const itTranslation = {
heroTitle: "UNP TOURS ZANZIBAR",
heroDesc: "Scopri i tour di lusso piu raffinati di Zanzibar e Tanzania, sport acquatici, artigianato e esperienze in santuari privati in piena liberta.",
heroBtn: "Prenota Esperienza VIP",
secTitle: "Le Nostre Esperienze Esclusive",
navExcursions: "Escursioni",
navWater: "Sport Acquatici",
navSafari: "Safari",
navArt: "Boutique",
navGarden: "Giardino Segreto",
navVote: "Vota",
navVip: "VIP",
navBook: "Prenota",
navContact: "Contatti",
navAbout: "Chi Siamo",
navGallery: "Galleria",
card1Title: "1. Escursioni a Zanzibar & Tour Storici",
card1Desc: "Visita le tartarughe giganti sull'Isola Prison, naviga con Safari Blue e passeggia per Stone Town.",
card2Title: "2. Santuario delle Scimmie Colobo di Jozani",
card2Desc: "Esplora il parco nazionale di Jozani e incontra le rare scimmie colobo rosse di Zanzibar.",
card3Title: "3. Noleggio Attrezzature & Veicoli",
card3Desc: "Noleggio auto di lusso, scooter, quad, attrezzatura da snorkeling e telecamere in hotel.",
card4Title: "4. Trasporto di Lusso & Transfer",
card4Desc: "Transfer VIP con autista in Alphard, Land Cruiser e van di lusso con Wi-Fi e aria condizionata.",
card5Title: "5. Opere d'Arte in Foglie di Banano",
card5Desc: "Opere d'arte con foglie di banano essiccate, raffiguranti la fauna africana.",
card6Title: "6. Safari Faunistici in Tanzania",
card6Desc: "Safari in aereo da Zanzibar verso i parchi nazionali della Tanzania, con voli e lodge.",
card7Title: "7. Tour Autentico della Citta",
card7Desc: "Esplora la cultura locale, i mercati di strada e l'architettura storica con guide esperte.",
card8Title: "8. Cena Romantica al Tramonto",
card8Desc: "Cena privata a lume di candela su spiagge bianche con musica dal vivo.",
card9Title: "9. Jet Ski, Jet Car & Kayak Drone",
card9Desc: "Jet Car e Jet Ski di lusso, insieme a kayak trasparenti con video drone.",
card10Title: "10. Giardino Segreto (L'Oasi Privata)",
card10Desc: "Santuario privato ultra-segreto per ospiti di alto profilo che cercano discrezione totale.",
aboutHeading: "Chi Siamo - UNP Tours",
aboutDesc: "Unique & Natural Paradise (UNP) e un operatore turistico di lusso con sede a Zanzibar, in Tanzania.",
aboutText1: "Fondata con la passione di mostrare il meglio di Zanzibar e della Tanzania, UNP Tours offre una collezione curata di esperienze esclusive.",
aboutText2: "Il nostro team di esperti locali si dedica a fornire un servizio personalizzato, assicurando che ogni viaggio sia su misura per i tuoi desideri.",
galleryHeading: "La Nostra Galleria",
galleryDesc: "Esplora la bellezza di Zanzibar e Tanzania attraverso il nostro obiettivo.",
voteHeading: "Vota la Tua Esperienza UNP Preferita",
voteDesc: "Aiutaci a servirti meglio! Valuta la tua attivita preferita:",
lblSelectExp: "Scegli Esperienza:",
lblRateStars: "Valuta la Tua Esperienza (1-5 Stelle):",
btnVoteSubmit: "Invia Valutazione",
vipHeading: "ESPERIENZA DI LUSSO UNP VIP",
vipDesc: "Goditi la massima discrezione, voli privati, maggiordomo personale e tour di lusso personalizzati.",
vipF1: "100% Discrezione",
vipF1Sub: "Check-in privato e non divulgazione.",
vipF2: "Voli Privati",
vipF2Sub: "Transfer e safari charter sull'isola.",
vipF3: "Maggiordomo Privato",
vipF3Sub: "Concierge personale dedicato 24/7.",
btnVipReq: "Prenota Concierge VIP",
bookHeading: "Modulo di Prenotazione Online",
bookDesc: "Prenota i tuoi tour, concierge VIP o giardino segreto via WhatsApp:",
lblGuestName: "Nome Completo:",
lblGuestContact: "Email / Numero di Telefono:",
lblGuestService: "Seleziona Esperienza:",
lblGuestDate: "Data Preferita:",
lblGuestCount: "Numero di Ospiti:",
lblGuestNotes: "Richieste Speciali:",
btnBookSubmit: "Invia Prenotazione via WhatsApp",
footerAbout: "Lusso a 10 stelle, avventura, opere d'arte artigianali a Zanzibar e in Tanzania.",
footerContactHead: "Contatto Diretto"
};
