const swTranslation = {
heroTitle: "UNP TOURS ZANZIBAR",
heroDesc: "Gundua ziara za kifahari za Zanzibar na Tanzania, michezo ya maji, sanaa za mikono, na sehemu za faragha kwa uhuru kamili.",
heroBtn: "Weka Miadi ya VIP",
secTitle: "Tajriba Zetu za Kipekee",
navExcursions: "Ziara",
navWater: "Michezo ya Maji",
navSafari: "Safari",
navArt: "Boutique",
navGarden: "Bustani ya Siri",
navVote: "Piga Kura",
navVip: "VIP",
navBook: "Weka Nafasi",
navContact: "Wasiliana",
navAbout: "Kuhusu Sisi",
navGallery: "Picha Zetu",
card1Title: "1. Ziara za Kihistoria Zanzibar",
card1Desc: "Tembelea kobe wakubwa kwenye Kisiwa cha Prison, safiri kwa Safari Blue, na tembea mitaa ya kihistoria ya Stone Town.",
card2Title: "2. Hifadhi ya Kima Wekundu wa Jozani",
card2Desc: "Chunguza msitu wa Jozani na uone kima wekundu wapkee wa Zanzibar.",
card3Title: "3. Kukodisha Vifaa na Magari",
card3Desc: "Kukodisha magari ya kifahari, pikipiki, baiskeli za matairi manne, na vifaa vya kuzamia hotelini kwako.",
card4Title: "4. Usafiri wa Kifahari",
card4Desc: "Usafiri wa VIP na dereva katika Alphards, Land Cruisers, na vans zenye Wi-Fi na kiyoyozi.",
card5Title: "5. Sanaa ya Mikono ya Majani ya Ndizi",
card5Desc: "Sanaa za kipekee zilizotengenezwa kwa majani ya ndizi yaliyokaushwa, zikionyesha wanyama wa Kiafrika.",
card6Title: "6. Safari za Wanyamapori Tanzania",
card6Desc: "Safari za ndege kutoka Zanzibar kwenda hifadhi maarufu za Tanzania, zikiwa na malazi ya kifahari.",
card7Title: "7. Ziara ya Mji na Utamaduni",
card7Desc: "Gundua utamaduni wa ndani, masoko ya vyakula vya mitaani, na majengo ya kihistoria na waongozaji wataalamu.",
card8Title: "8. Chakula cha Jioni cha Kimapenzi",
card8Desc: "Chakula cha faragha cha baharini kwa mishumaa ufukweni mwa bahari na muziki wa moja kwa moja.",
card9Title: "9. Jet Ski, Jet Car na Kayak ya Drone",
card9Desc: "Jet Cars na Jet Skis za kifahari, pamoja na kayak za uwazi zenye rekodi ya video ya drone.",
card10Title: "10. Bustani ya Siri (Faragha Kamili)",
card10Desc: "Sehemu ya siri ya kifahari kwa wageni wanaotaka faragha kamili, huduma ya msaidizi binafsi, na uhuru kamili.",
aboutHeading: "Kuhusu UNP Tours",
aboutDesc: "Unique & Natural Paradise (UNP) ni kampuni ya kifahari ya utalii iliyopo Zanzibar, Tanzania.",
aboutText1: "Ilianzishwa kwa shauku ya kuonyesha uzuri wa Zanzibar na Tanzania, UNP Tours inatoa mkusanyiko wa tajriba za kipekee - kutoka ziara za kihistoria za Stone Town hadi safari za wanyamapori na chakula cha jioni cha kifahari ufukweni.",
aboutText2: "Timu yetu ya wataalamu wa ndani imejitolea kutoa huduma binafsi, kuhakikisha kila safari inakidhi matakwa yako. Iwe unatafuta adventure, mapumziko, au faragha kamili, tuko hapa kufanya likizo yako ya ndoto iwe kweli.",
galleryHeading: "Picha Zetu",
galleryDesc: "Chunguza uzuri wa Zanzibar na Tanzania kupitia lenzi yetu.",
voteHeading: "Piga Kura kwa Tajriba Yako Unayoipenda",
voteDesc: "Tusaidie kukuhudumia vizuri! Weka alama kwa shughuli unayoipenda:",
lblSelectExp: "Chagua Tajriba:",
lblRateStars: "Weka Nyota (1 hadi 5):",
btnVoteSubmit: "Tuma Kura",
vipHeading: "TAJRIBA YA KIFAHARI YA UNP VIP",
vipDesc: "Furahia faragha kamili, safari za ndege za kibinafsi, msaidizi binafsi, na safari za kifahari zilizoundwa maalum kwa wateja wa hali ya juu.",
vipF1: "Faragha ya 100%",
vipF1Sub: "Kuingia kwa faragha na huduma ya siri.",
vipF2: "Ndege za Kibinafsi",
vipF2Sub: "Usafiri wa ndege wa kukodi na safari za kisiwani.",
vipF3: "Msaidizi Binafsi",
vipF3Sub: "Msaidizi wa kibinafsi masaa 24/7.",
btnVipReq: "Omba Msaidizi wa VIP",
bookHeading: "Fomu ya Kuweka Nafasi Mtandaoni",
bookDesc: "Weka nafasi ya ziara zako, msaidizi wa VIP, au bustani ya siri kupitia WhatsApp:",
lblGuestName: "Jina Lako Kamili:",
lblGuestContact: "Barua Pepe / Namba ya Simu:",
lblGuestService: "Chagua Tajriba / Kifurushi:",
lblGuestDate: "Tarehe Unayotaka:",
lblGuestCount: "Idadi ya Wageni:",
lblGuestNotes: "Maombi Maalum au Vidokezo:",
btnBookSubmit: "Thibitisha Nafasi kupitia WhatsApp",
footerAbout: "Kifahari cha nyota 10, adventure, sanaa za mikono, na tajriba za faragha Zanzibar na Tanzania.",
footerContactHead: "Mawasiliano ya Moja kwa Moja"
};
