const deTranslation = {
heroTitle: "UNP TOURS ZANZIBAR",
heroDesc: "Entdecken Sie die exklusivsten Luxustouren von Sansibar und Tansania, Wassersport, handgefertigte Kunst und private Ruckzugsorter in volliger Freiheit.",
heroBtn: "VIP-Erlebnis Buchen",
secTitle: "Unsere Exklusiven Erlebnisse",
navExcursions: "Ausfluge",
navWater: "Wassersport",
navSafari: "Safaris",
navArt: "Boutique",
navGarden: "Geheimer Garten",
navVote: "Abstimmung",
navVip: "VIP",
navBook: "Buchen",
navContact: "Kontakt",
navAbout: "Uber Uns",
navGallery: "Galerie",
card1Title: "1. Sansibar-Ausfluge & Historische Touren",
card1Desc: "Besuchen Sie die Riesenschildkroten auf Prison Island, segeln Sie mit Safari Blue und erkunden Sie Stone Town.",
card2Title: "2. Jozani Naturschutzgebiet fur Rote Colobus-Affen",
card2Desc: "Erkunden Sie den Nationalpark Jozani und treffen Sie die seltenen roten Colobus-Affen.",
card3Title: "3. Ausrustung & Fahrzeugvermietung",
card3Desc: "Luxusautovermietung, Roller, Quads, Schnorchelausrustung und Kameras zu Ihrem Hotel.",
card4Title: "4. Luxustransporter & Transfers",
card4Desc: "VIP-Chauffeurtransfers in Luxus-Alphards, Land Cruisern und Vans mit WLAN und Klimaanlage.",
card5Title: "5. Handgefertigte Kunst aus Bananenblattern",
card5Desc: "Handgefertigte Kunstwerke aus getrockneten Bananenblattern, die die afrikanische Tierwelt darstellen.",
card6Title: "6. Wildtier-Safaris in Tansania",
card6Desc: "Fly-in-Safaris von Sansibar zu den Nationalparks Tansanias, inklusive Flugen und Luxuslodges.",
card7Title: "7. Authentische Stadttour",
card7Desc: "Erkunden Sie die lokale Kultur, Streetfood-Markte und historische Architektur mit erfahrenen Reiseleitern.",
card8Title: "8. Romantisches Abendessen bei Sonnenuntergang",
card8Desc: "Privates Abendessen bei Kerzenschein an weissen Sandstranden mit Live-Musik.",
card9Title: "9. Jet Ski, Jet Car & Drohnen-Kajak",
card9Desc: "Luxus-Jet Cars und Jet Skis sowie transparente Kajaks mit Drohnen-Videoaufnahmen.",
card10Title: "10. Geheimer Garten (Die Private Oase)",
card10Desc: "Ultra-privater Ruckzugsort fur prominente Gaste, die absolute Diskretion suchen.",
aboutHeading: "Uber UNP Tours",
aboutDesc: "Unique & Natural Paradise (UNP) ist ein erstklassiger Luxusreiseveranstalter mit Sitz in Sansibar, Tansania.",
aboutText1: "UNP Tours wurde mit der Leidenschaft gegrundet, das Beste von Sansibar und Tansania zu prasentieren, und bietet eine kuratierte Sammlung exklusiver Erlebnisse.",
aboutText2: "Unser Team lokaler Experten ist bestrebt, einen personalisierten Service zu bieten und sicherzustellen, dass jede Reise auf Ihre Wunsche zugeschnitten ist.",
galleryHeading: "Unsere Galerie",
galleryDesc: "Entdecken Sie die Schonheit von Sansibar und Tansania durch unsere Linse.",
voteHeading: "Stimmen Sie fur Ihr Lieblings-UNP-Erlebnis",
voteDesc: "Helfen Sie uns, besser zu dienen! Bewerten Sie Ihre Lieblingsaktivitat:",
lblSelectExp: "Erlebnis Wahlen:",
lblRateStars: "Bewerten Sie Ihr Erlebnis (1-5 Sterne):",
btnVoteSubmit: "Bewertung Absenden",
vipHeading: "UNP VIP LUXUS-ERLEBNIS",
vipDesc: "Geniessen Sie maximale Diskretion, private Flugbuchungen, personlichen Butlerservice und Luxustouren.",
vipF1: "100% Diskretion",
vipF1Sub: "Privater Check-in und Geheimhaltungsservice.",
vipF2: "Privatfluge",
vipF2Sub: "Charter-Transfers und Safaris auf der Insel.",
vipF3: "Privater Butler",
vipF3Sub: "24/7 dedizierter personlicher Concierge.",
btnVipReq: "VIP-Concierge Reservieren",
bookHeading: "Online-Buchungsformular",
bookDesc: "Buchen Sie Ihre Touren, VIP-Concierge oder den geheimen Garten uber WhatsApp:",
lblGuestName: "Vollstandiger Name:",
lblGuestContact: "E-Mail / Telefonnummer:",
lblGuestService: "Erlebnis Auswahlen:",
lblGuestDate: "Bevorzugtes Datum:",
lblGuestCount: "Anzahl der Gaste:",
lblGuestNotes: "Besondere Wunsche:",
btnBookSubmit: "Buchung uber WhatsApp Senden",
footerAbout: "10-Sterne-Luxus, Abenteuer, handgefertigte Kunst in Sansibar und Tansania.",
footerContactHead: "Direkter Kontakt"
};
