var laTranslation = {
    heroTitle: "UNP TOURS ZANZIBAR",
    heroDesc: "Detegere Zanzibar et Tanzania luxuriosissimas itinera, ludos aquaticos, artificia manu facta, et privata sanctuaria experientias in plena libertate.",
    heroBtn: "Libri VIP Experientia",
    secTitle: "Nostrae Exclusivae Experientiae",
    navExcursions: "Excursiones", navWater: "Ludi Aquatici", navSafari: "Safari",
    navArt: "Boutique", navGarden: "Hortus Secretus", navAbout: "De Nobis",
    navGallery: "Pinacotheca", navVote: "Votum", navVip: "VIP", navBook: "Libri", navContact: "Contactus",
    card1Title: "1. Excursiones Historicae Zanzibar",
    card1Desc: "Visita testudines gigantes, naviga in Safari Blue, et ambula in Stone Town.",
    card2Title: "2. Sanctuarium Simiarum Colobus Jozani",
    card2Desc: "Explora Silvam Jozani et occurre raris simiis Colobus rubris Zanzibar propriis.",
    card3Title: "3. Instrumenta et Vehicula Locationis",
    card3Desc: "Locationes carrorum, scooterorum, quad bike, instrumentorum snorkeling et camerarum.",
    card4Title: "4. Transportatio et Translatio Luxuriosa",
    card4Desc: "Translatio VIP in Alphards, Land Cruisers, et vans cum Wi-Fi et A/C.",
    card5Title: "5. Artificia Manu Facta ex Foliis Musarum",
    card5Desc: "Artificia ex foliis musarum siccatis, depingens vitam feram Africanam et culturam.",
    card6Title: "6. Safari Vitae Ferae Tanzania",
    card6Desc: "Safari volantes ex Zanzibar ad parcos nationales Tanzaniae cum volatu et hospitiis.",
    card7Title: "7. Itinera Autentica Urbis",
    card7Desc: "Explora culturam localem, mercatus cibi, et architecturam historicam cum ducibus expertis.",
    card8Title: "8. Cena Romantica in Litore Occasum Solis",
    card8Desc: "Privata cena maritima ad lumina candelarum in litoribus arenosis albis cum musica viva.",
    card9Title: "9. Jet Ski, Jet Car, et Drone Kayak",
    card9Desc: "Jet Cars luxuriosi, Jet Skis, et kayaks transparentes cum video drone aeria.",
    card10Title: "10. Hortus Secretus (Oasis Privata)",
    card10Desc: "Sanctuarium ultra-privatum pro hospitibus illustribus quaerentibus 100% discretionem.",
    aboutHeading: "De UNP Tours",
    aboutDesc: "Unique & Natural Paradise (UNP) est primarius operator luxuriosus in Zanzibar, Tanzania.",
    aboutText1: "Fundata cum passione ad ostendendum optimum Zanzibar et Tanzania, UNP Tours offert collectionem curatam experientiarum exclusivarum.",
    aboutText2: "Nostra turma peritorum localium dedicata est ad praebendum servitium personalizatum.",
    galleryHeading: "Nostra Pinacotheca",
    galleryDesc: "Explora pulchritudinem Zanzibar et Tanzania per nostram lentem.",
    voteHeading: "Vota Tuam Experientiam UNP Favorabilem",
    voteDesc: "Adiuva nos melius servire! Aestima activitatem tuam favorabilem infra:",
    lblSelectExp: "Elige Experientiam:",
    lblRateStars: "Aestima Experientiam Tuam (1 ad 5 Stellas):",
    btnVoteSubmit: "Submitte Aestimationem",
    vipHeading: "UNP VIP EXPERIENTIA LUXURIOSA",
    vipDesc: "Fruere maxima discretione, libris volatuum privatorum, servitio butleri personalis, et itinera luxuriosa custom facta.",
    vipF1: "100% Discretio", vipF1Sub: "Check-in privata et servitium non-divulgationis.",
    vipF2: "Volatus Privati", vipF2Sub: "Translatio insulae charter et safari.",
    vipF3: "Butler Privatus", vipF3Sub: "Concierge personalis dedicatus 24/7.",
    btnVipReq: "Reserva VIP Concierge",
    bookHeading: "Forma Libri Online",
    bookDesc: "Libri tuas excursiones, VIP concierge, vel Hortum Secretum statim per WhatsApp:",
    lblGuestName: "Nomen Completum:",
    lblGuestContact: "Email / Numerus Telephonicus:",
    lblGuestService: "Elige Experientiam / Fasciculum:",
    lblGuestDate: "Diem Preferatum:",
    lblGuestCount: "Numerus Hospitum:",
    lblGuestNotes: "Postulationes Speciales vel Notae:",
    btnBookSubmit: "Submitte Libri per WhatsApp",
    footerAbout: "10-Stella luxuria, adventura, artificia organica manu facta, et experientiae sanctuarii in Zanzibar et Tanzania.",
    footerContactHead: "Contactus Directus"
};
