const enTranslation = {
heroTitle: "UNP TOURS ZANZIBAR",
heroDesc: "Discover Zanzibar & Tanzania's most exquisite luxury tours, water sports, handmade artwork, and private sanctuary experiences in full freedom.",
heroBtn: "Book VIP Experience",
secTitle: "Our Exclusive Experiences",
navExcursions: "Excursions",
navWater: "Water Sports",
navSafari: "Safaris",
navArt: "Boutique",
navGarden: "Secret Garden",
navVote: "Vote",
navVip: "VIP",
navBook: "Book",
navContact: "Contact",
navAbout: "About",
navGallery: "Gallery",
card1Title: "1. Zanzibar Excursions & Historic Tours",
card1Desc: "Visit giant tortoises on Prison Island, sail on Safari Blue, and walk Stone Town.",
card2Title: "2. Jozani Red Colobus Monkey Sanctuary",
card2Desc: "Explore Jozani Forest and encounter rare Red Colobus Monkeys unique to Zanzibar.",
card3Title: "3. Equipment & Vehicle Rentals",
card3Desc: "Car rentals, scooters, quad bikes, snorkeling gear, and cameras to your hotel.",
card4Title: "4. Luxury Transporter & Transfers",
card4Desc: "VIP chauffeur transfers in Alphards, Land Cruisers, and vans with Wi-Fi and A/C.",
card5Title: "5. Handmade Banana Leaf Artwork",
card5Desc: "Artwork using real dried banana leaves, depicting African wildlife and culture.",
card6Title: "6. Tanzania Wildlife Safaris",
card6Desc: "Fly-in safaris from Zanzibar to Tanzania's national parks with flights and lodges.",
card7Title: "7. Authentic City Tour",
card7Desc: "Explore local culture, street food markets, and historic architecture with expert guides.",
card8Title: "8. Sunset Romantic Beach Dinner",
card8Desc: "Private candlelit seafood dinner on white sand beaches with live music.",
card9Title: "9. Jet Ski, Jet Car & Drone Kayak",
card9Desc: "Luxury Jet Cars, Jet Skis, and transparent kayaks with aerial drone video.",
card10Title: "10. Secret Garden (The Private Oasis)",
card10Desc: "Ultra-private sanctuary for high-profile guests seeking 100% discretion.",
aboutHeading: "About UNP Tours",
aboutDesc: "Unique & Natural Paradise (UNP) is a premier luxury tour operator based in Zanzibar, Tanzania.",
aboutText1: "Founded with a passion for showcasing the very best of Zanzibar and Tanzania, UNP Tours offers a curated collection of exclusive experiences — from historic Stone Town tours and wildlife safaris to luxury beach dinners and private sanctuary retreats.",
aboutText2: "Our team of local experts is dedicated to providing personalized service, ensuring every journey is tailored to your desires. Whether you seek adventure, relaxation, or complete discretion, we are here to make your dream holiday a reality.",
galleryHeading: "Our Gallery",
galleryDesc: "Explore the beauty of Zanzibar & Tanzania through our lens.",
voteHeading: "Vote Your Favorite UNP Experience",
voteDesc: "Help us serve you better! Rate your favorite activity below:",
lblSelectExp: "Choose Experience:",
lblRateStars: "Rate Your Experience (1 to 5 Stars):",
btnVoteSubmit: "Submit Rating",
vipHeading: "UNP VIP LUXURY EXPERIENCE",
vipDesc: "Enjoy maximum discretion, private flight bookings, personal butler service, and custom luxury tours designed for high-net-worth clients.",
vipF1: "100% Discretion",
vipF1Sub: "Private check-ins & non-disclosure service.",
vipF2: "Private Flights",
vipF2Sub: "Chartered island transfers & safaris.",
vipF3: "Private Butler",
vipF3Sub: "24/7 dedicated personal concierge.",
btnVipReq: "Reserve VIP Concierge",
bookHeading: "Book Online Form",
bookDesc: "Book your tours, VIP concierge, or Secret Garden sanctuary instantly via WhatsApp:",
lblGuestName: "Full Name:",
lblGuestContact: "Email Address / Phone Number:",
lblGuestService: "Select Experience / Package:",
lblGuestDate: "Preferred Date:",
lblGuestCount: "Number of Guests:",
lblGuestNotes: "Special Requests or Notes:",
btnBookSubmit: "Submit Booking via WhatsApp",
footerAbout: "10-Star luxury, adventure, handmade organic artwork, and sanctuary experiences in Zanzibar & Tanzania.",
footerContactHead: "Direct Contact"
};
