var jaTranslation = {
    heroTitle: "UNPツアーズ ザンジバル",
    heroDesc: "ザンジバルとタンザニアの最も豪華なラグジュアリーツアー、ウォータースポーツ、手作りアート、プライベートサンクチュアリ体験を発見してください。",
    heroBtn: "VIP体験を予約する",
    secTitle: "私たちの特別な体験",
    navExcursions: "エクスカーション", navWater: "ウォータースポーツ", navSafari: "サファリ",
    navArt: "ブティック", navGarden: "秘密の庭", navAbout: "私たちについて",
    navGallery: "ギャラリー", navVote: "投票", navVip: "VIP", navBook: "予約", navContact: "お問い合わせ",
    card1Title: "1. ザンジバル歴史ツアー",
    card1Desc: "巨大なカメを訪ね、サファリブルーを楽しみ、ストーンタウンを散策しましょう。",
    card2Title: "2. ジョザニ・アカコロブスモンキーサンクチュアリ",
    card2Desc: "ジョザニの森を探索し、ザンジバル特有の珍しいアカコロブスザルに出会いましょう。",
    card3Title: "3. 設備と車両のレンタル",
    card3Desc: "レンタカー、スクーター、四輪バギー、シュノーケリング用具、カメラ。",
    card4Title: "4. ラグジュアリートランスポーターと送迎",
    card4Desc: "Wi-Fiとエアコン完備のアルファード、ランドクルーザー、バンでのVIP送迎。",
    card5Title: "5. 手作りバナナリーフアート",
    card5Desc: "本物の乾燥バナナの葉を使用したアート、アフリカの野生動物を描いています。",
    card6Title: "6. タンザニア野生動物サファリ",
    card6Desc: "ザンジバルからタンザニアの国立公園へのフライインサファリ。",
    card7Title: "7. 本格的なシティツアー",
    card7Desc: "地元の文化、ストリートフードマーケット、歴史的建築物を探索しましょう。",
    card8Title: "8. 夕日ロマンチックビーチディナー",
    card8Desc: "白い砂浜でのプライベートなキャンドルライトシーフードディナーとライブミュージック。",
    card9Title: "9. ジェットスキー、ジェットカー、ドローンカヤック",
    card9Desc: "豪華なジェットカー、ジェットスキー、透明カヤックと空中ドローン映像。",
    card10Title: "10. 秘密の庭（プライベートオアシス）",
    card10Desc: "100%のプライバシーを求めるVIPゲストのための超プライベートサンクチュアリ。",
    aboutHeading: "UNPツアーズについて",
    aboutDesc: "Unique & Natural Paradise (UNP) は、タンザニアのザンジバルに拠点を置く一流のラグジュアリーツアーオペレーターです。",
    aboutText1: "ザンジバルとタンザニアの最高のものを紹介する情熱を持って設立されたUNPツアーズは、厳選された特別な体験を提供しています。",
    aboutText2: "地元の専門家チームがパーソナライズされたサービスを提供することに専念しています。",
    galleryHeading: "私たちのギャラリー",
    galleryDesc: "私たちのレンズを通してザンジバルとタンザニアの美しさを探検してください。",
    voteHeading: "お気に入りのUNP体験に投票してください",
    voteDesc: "より良いサービスを提供するためにご協力ください！以下であなたの好きなアクティビティを評価してください：",
    lblSelectExp: "体験を選択：",
    lblRateStars: "体験を評価（1〜5つ星）：",
    btnVoteSubmit: "評価を送信",
    vipHeading: "UNP VIPラグジュアリー体験",
    vipDesc: "最大限のプライバシー、プライベートフライト予約、専属バトラーサービス、カスタムラグジュアリーツアーをお楽しみください。",
    vipF1: "100%のプライバシー", vipF1Sub: "プライベートチェックインと秘密保持サービス。",
    vipF2: "プライベートフライト", vipF2Sub: "チャーター島送迎とサファリ。",
    vipF3: "専属バトラー", vipF3Sub: "24時間365日専任のパーソナルコンシェルジュ。",
    btnVipReq: "VIPコンシェルジュを予約する",
    bookHeading: "オンライン予約フォーム",
    bookDesc: "ツアー、VIPコンシェルジュ、秘密の庭をWhatsAppで即座に予約：",
    lblGuestName: "氏名：",
    lblGuestContact: "メールアドレス / 電話番号：",
    lblGuestService: "体験 / パッケージを選択：",
    lblGuestDate: "希望日：",
    lblGuestCount: "ゲスト数：",
    lblGuestNotes: "特別なリクエストやメモ：",
    btnBookSubmit: "WhatsAppで予約を送信",
    footerAbout: "10つ星のラグジュアリー、アドベンチャー、手作りオーガニックアート、ザンジバルとタンザニアのサンクチュアリ体験。",
    footerContactHead: "直接お問い合わせ"
};
