var ptTranslation = {
    heroTitle: "UNP TOURS ZANZIBAR",
    heroDesc: "Descubra os passeios de luxo, esportes aquáticos, artesanato e experiências privadas de Zanzibar e Tanzânia.",
    heroBtn: "Reservar Experiência VIP",
    secTitle: "Nossas Experiências Exclusivas",
    navExcursions: "Excursões", navWater: "Esportes Aquáticos", navSafari: "Safáris",
    navArt: "Boutique", navGarden: "Jardim Secreto", navAbout: "Sobre Nós",
    navGallery: "Galeria", navVote: "Votar", navVip: "VIP", navBook: "Reservar", navContact: "Contato",
    card1Title: "1. Excursões Históricas de Zanzibar",
    card1Desc: "Visite tartarugas gigantes, faça o Safari Blue e caminhe por Stone Town.",
    card2Title: "2. Santuário de Macacos Colobus de Jozani",
    card2Desc: "Explore a Floresta de Jozani e encontre macacos Colobus vermelhos únicos.",
    card3Title: "3. Aluguel de Equipamentos e Veículos",
    card3Desc: "Aluguel de carros, scooters, quadriciclos, equipamento de snorkel e câmeras.",
    card4Title: "4. Transporte e Traslados de Luxo",
    card4Desc: "Traslados VIP com motorista em Alphards, Land Cruisers e vans com Wi-Fi e A/C.",
    card5Title: "5. Arte em Folhas de Bananeira Feita à Mão",
    card5Desc: "Arte usando folhas de bananeira secas reais, retratando a vida selvagem africana.",
    card6Title: "6. Safáris de Vida Selvagem na Tanzânia",
    card6Desc: "Safáris aéreos de Zanzibar para os parques nacionais da Tanzânia.",
    card7Title: "7. Tour Autêntico pela Cidade",
    card7Desc: "Explore a cultura local, mercados de comida e arquitetura histórica.",
    card8Title: "8. Jantar Romântico ao Pôr do Sol",
    card8Desc: "Jantar privado à luz de velas em praias de areia branca com música ao vivo.",
    card9Title: "9. Jet Ski, Jet Car e Caiaque com Drone",
    card9Desc: "Jet Cars de luxo, Jet Skis e caiaques transparentes com vídeo aéreo de drone.",
    card10Title: "10. Jardim Secreto (O Oásis Privado)",
    card10Desc: "Santuário ultraprivado para hóspedes de alto perfil que buscam discrição total.",
    aboutHeading: "Sobre a UNP Tours",
    aboutDesc: "Unique & Natural Paradise (UNP) é uma operadora de turismo de luxo baseada em Zanzibar, Tanzânia.",
    aboutText1: "Fundada com paixão por mostrar o melhor de Zanzibar e Tanzânia, a UNP Tours oferece uma coleção de experiências exclusivas.",
    aboutText2: "Nossa equipe de especialistas locais se dedica a fornecer um serviço personalizado.",
    galleryHeading: "Nossa Galeria",
    galleryDesc: "Explore a beleza de Zanzibar e Tanzânia através das nossas lentes.",
    voteHeading: "Vote na sua experiência UNP favorita",
    voteDesc: "Ajude-nos a servi-lo melhor! Avalie sua atividade favorita abaixo:",
    lblSelectExp: "Escolha a Experiência:",
    lblRateStars: "Avalie sua Experiência (1 a 5 estrelas):",
    btnVoteSubmit: "Enviar Avaliação",
    vipHeading: "EXPERIÊNCIA DE LUXO VIP UNP",
    vipDesc: "Desfrute de máxima discrição, voos privados, serviço de mordomo e passeios de luxo personalizados.",
    vipF1: "Discrição 100%", vipF1Sub: "Check-in privado e serviço de confidencialidade.",
    vipF2: "Voos Privados", vipF2Sub: "Traslados e safáris charter.",
    vipF3: "Mordomo Privado", vipF3Sub: "Concierge pessoal dedicado 24/7.",
    btnVipReq: "Reservar Concierge VIP",
    bookHeading: "Formulário de Reserva Online",
    bookDesc: "Reserve seus passeios, concierge VIP ou jardim secreto instantaneamente via WhatsApp:",
    lblGuestName: "Nome Completo:",
    lblGuestContact: "E-mail / Número de Telefone:",
    lblGuestService: "Selecione Experiência / Pacote:",
    lblGuestDate: "Data Preferida:",
    lblGuestCount: "Número de Hóspedes:",
    lblGuestNotes: "Pedidos Especiais ou Notas:",
    btnBookSubmit: "Enviar Reserva via WhatsApp",
    footerAbout: "Luxo de 10 estrelas, aventura, arte orgânica feita à mão e santuários em Zanzibar e Tanzânia.",
    footerContactHead: "Contato Direto"
};
