var koTranslation = {
    heroTitle: "UNP 투어 잔지바르",
    heroDesc: "잔지바르와 탄자니아의 가장 호화로운 럭셔리 투어, 수상 스포츠, 수제 예술품, 프라이빗 안식처 경험을 발견하세요.",
    heroBtn: "VIP 경험 예약",
    secTitle: "우리의 독점적인 경험",
    navExcursions: "여행", navWater: "수상 스포츠", navSafari: "사파리",
    navArt: "부티크", navGarden: "비밀 정원", navAbout: "소개",
    navGallery: "갤러리", navVote: "투표", navVip: "VIP", navBook: "예약", navContact: "연락처",
    card1Title: "1. 잔지바르 역사 투어",
    card1Desc: "거대 거북이를 방문하고 사파리 블루를 즐기고 스톤 타운을 산책하세요.",
    card2Title: "2. 조자니 레드 콜로버스 원숭이 안식처",
    card2Desc: "조자니 숲을 탐험하고 잔지바르 고유의 희귀 레드 콜로버스 원숭이를 만나보세요.",
    card3Title: "3. 장비 및 차량 대여",
    card3Desc: "렌터카, 스쿠터, 쿼드 바이크, 스노클링 장비 및 카메라.",
    card4Title: "4. 럭셔리 운송 및 이동",
    card4Desc: "Wi-Fi와 에어컨이 완비된 알파드, 랜드 크루저, 밴으로 VIP 기사 이동.",
    card5Title: "5. 수제 바나나 잎 예술품",
    card5Desc: "실제 건조 바나나 잎을 사용한 예술품으로 아프리카 야생 동물을 묘사합니다.",
    card6Title: "6. 탄자니아 야생 동물 사파리",
    card6Desc: "잔지바르에서 탄자니아 국립공원으로 가는 비행 사파리.",
    card7Title: "7. 진정한 도시 투어",
    card7Desc: "현지 문화, 길거리 음식 시장, 역사적인 건축물을 탐험하세요.",
    card8Title: "8. 일몰 로맨틱 해변 저녁 식사",
    card8Desc: "백사장에서 라이브 음악과 함께하는 프라이빗 촛불 해산물 저녁 식사.",
    card9Title: "9. 제트 스키, 제트 카 및 드론 카약",
    card9Desc: "럭셔리 제트 카, 제트 스키, 투명 카약과 항공 드론 비디오.",
    card10Title: "10. 비밀 정원 (프라이빗 오아시스)",
    card10Desc: "100% 프라이버시를 추구하는 고위급 게스트를 위한 초프라이빗 안식처.",
    aboutHeading: "UNP 투어 소개",
    aboutDesc: "Unique & Natural Paradise (UNP)는 탄자니아 잔지바르에 본사를 둔 최고급 럭셔리 투어 운영업체입니다.",
    aboutText1: "잔지바르와 탄자니아의 최고를 선보이려는 열정으로 설립된 UNP 투어는 엄선된 독점 경험을 제공합니다.",
    aboutText2: "현지 전문가 팀이 맞춤형 서비스를 제공하기 위해 최선을 다하고 있습니다.",
    galleryHeading: "우리 갤러리",
    galleryDesc: "우리의 렌즈를 통해 잔지바르와 탄자니아의 아름다움을 탐험해보세요.",
    voteHeading: "가장 좋아하는 UNP 경험에 투표하세요",
    voteDesc: "더 나은 서비스를 제공할 수 있도록 도와주세요! 아래에서 가장 좋아하는 활동을 평가해주세요:",
    lblSelectExp: "경험 선택:",
    lblRateStars: "경험 평가 (1~5성):",
    btnVoteSubmit: "평가 제출",
    vipHeading: "UNP VIP 럭셔리 경험",
    vipDesc: "최대한의 프라이버시, 전용 항공편 예약, 개인 버틀러 서비스, 맞춤형 럭셔리 투어를 즐기세요.",
    vipF1: "100% 프라이버시", vipF1Sub: "프라이빗 체크인 및 비밀 유지 서비스.",
    vipF2: "전용 항공편", vipF2Sub: "전세 섬 이동 및 사파리.",
    vipF3: "개인 버틀러", vipF3Sub: "24/7 전담 개인 컨시어지.",
    btnVipReq: "VIP 컨시어지 예약",
    bookHeading: "온라인 예약 양식",
    bookDesc: "투어, VIP 컨시어지 또는 비밀 정원을 WhatsApp을 통해 즉시 예약하세요:",
    lblGuestName: "성명:",
    lblGuestContact: "이메일 주소 / 전화번호:",
    lblGuestService: "경험 / 패키지 선택:",
    lblGuestDate: "희망 날짜:",
    lblGuestCount: "게스트 수:",
    lblGuestNotes: "특별 요청 또는 메모:",
    btnBookSubmit: "WhatsApp을 통해 예약 제출",
    footerAbout: "10성급 럭셔리, 모험, 수제 유기농 예술품, 잔지바르와 탄자니아의 안식처 경험.",
    footerContactHead: "직접 연락"
};
