var esTranslation = {
    heroTitle: "UNP TOURS ZANZIBAR",
    heroDesc: "Descubra los tours de lujo, deportes acuáticos, artesanías y experiencias privadas de Zanzíbar y Tanzania.",
    heroBtn: "Reservar Experiencia VIP",
    secTitle: "Nuestras Experiencias Exclusivas",
    navExcursions: "Excursiones", navWater: "Deportes Acuáticos", navSafari: "Safaris",
    navArt: "Boutique", navGarden: "Jardín Secreto", navAbout: "Sobre Nosotros",
    navGallery: "Galería", navVote: "Votar", navVip: "VIP", navBook: "Reservar", navContact: "Contacto",
    card1Title: "1. Excursiones Históricas de Zanzíbar",
    card1Desc: "Visite tortugas gigantes, haga Safari Blue y camine por Stone Town.",
    card2Title: "2. Santuario de Monos Colobus de Jozani",
    card2Desc: "Explore el bosque de Jozani y encuentre monos Colobus rojos únicos.",
    card3Title: "3. Alquiler de Equipos y Vehículos",
    card3Desc: "Alquiler de coches, scooters, quads, equipo de snorkel y cámaras.",
    card4Title: "4. Transporte y Traslados de Lujo",
    card4Desc: "Traslados VIP con chófer en Alphards, Land Cruisers y furgonetas con Wi-Fi y A/C.",
    card5Title: "5. Arte en Hojas de Plátano Hecho a Mano",
    card5Desc: "Arte con hojas de plátano secas reales, que representan la fauna africana.",
    card6Title: "6. Safaris de Vida Silvestre en Tanzania",
    card6Desc: "Safaris aéreos desde Zanzíbar a los parques nacionales de Tanzania.",
    card7Title: "7. Tour Auténtico por la Ciudad",
    card7Desc: "Explore la cultura local, mercados de comida y arquitectura histórica.",
    card8Title: "8. Cena Romántica al Atardecer",
    card8Desc: "Cena privada a la luz de las velas en playas de arena blanca con música en vivo.",
    card9Title: "9. Jet Ski, Jet Car y Kayak con Dron",
    card9Desc: "Jet Cars de lujo, Jet Skis y kayaks transparentes con video aéreo de dron.",
    card10Title: "10. Jardín Secreto (El Oasis Privado)",
    card10Desc: "Santuario ultraprivado para huéspedes de alto perfil que buscan total discreción.",
    aboutHeading: "Sobre UNP Tours",
    aboutDesc: "Unique & Natural Paradise (UNP) es un operador turístico de lujo con sede en Zanzíbar, Tanzania.",
    aboutText1: "Fundada con pasión por mostrar lo mejor de Zanzíbar y Tanzania, UNP Tours ofrece una colección de experiencias exclusivas.",
    aboutText2: "Nuestro equipo de expertos locales se dedica a brindar un servicio personalizado.",
    galleryHeading: "Nuestra Galería",
    galleryDesc: "Explore la belleza de Zanzíbar y Tanzania a través de nuestra lente.",
    voteHeading: "Vote por su experiencia UNP favorita",
    voteDesc: "¡Ayúdenos a servirle mejor! Califique su actividad favorita a continuación:",
    lblSelectExp: "Elija Experiencia:",
    lblRateStars: "Califique su Experiencia (1 a 5 estrellas):",
    btnVoteSubmit: "Enviar Calificación",
    vipHeading: "EXPERIENCIA DE LUJO VIP UNP",
    vipDesc: "Disfrute de máxima discreción, vuelos privados, servicio de mayordomo y tours de lujo personalizados.",
    vipF1: "Discreción 100%", vipF1Sub: "Check-in privado y servicio de confidencialidad.",
    vipF2: "Vuelos Privados", vipF2Sub: "Traslados y safaris chárter.",
    vipF3: "Mayordomo Privado", vipF3Sub: "Conserje personal dedicado 24/7.",
    btnVipReq: "Reservar Conserje VIP",
    bookHeading: "Formulario de Reserva en Línea",
    bookDesc: "Reserve sus tours, conserje VIP o jardín secreto al instante por WhatsApp:",
    lblGuestName: "Nombre Completo:",
    lblGuestContact: "Correo Electrónico / Teléfono:",
    lblGuestService: "Seleccione Experiencia / Paquete:",
    lblGuestDate: "Fecha Preferida:",
    lblGuestCount: "Número de Huéspedes:",
    lblGuestNotes: "Solicitudes Especiales o Notas:",
    btnBookSubmit: "Enviar Reserva por WhatsApp",
    footerAbout: "Lujo de 10 estrellas, aventura, arte orgánico hecho a mano y santuarios en Zanzíbar y Tanzania.",
    footerContactHead: "Contacto Directo"
};
